package anthropic

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/mrgeoffrich/agent-harness/internal/wire"
)

// TestLiveMessagesAPI drives the real Messages API by hand — never run by
// scripts/test.sh or scripts/build.sh, which never set
// RUN_ANTHROPIC_LIVE_TEST. Run it explicitly:
//
//	set -a; source ~/.config/agent-harness/anthropic.env; set +a
//	RUN_ANTHROPIC_LIVE_TEST=1 go test ./internal/anthropic -run TestLiveMessagesAPI -v
//
// It exercises, per model: a tool call followed by a second sub-turn that
// replays the first sub-turn's raw provider blocks (thinking included) and
// a byte-identical system prompt long enough to clear every model's cache
// minimum, so the second request's usage shows a cache read. A single web
// search, on Sonnet 5 only, covers server-tool replay for every model's
// shared request-building code without tripling the search spend. Findings
// go in docs/OBSERVED.md, transcribed from this test's -v output rather
// than generated by it, so the file states what a person confirmed rather
// than what a script printed.
func TestLiveMessagesAPI(t *testing.T) {
	if os.Getenv("RUN_ANTHROPIC_LIVE_TEST") == "" {
		t.Skip("set RUN_ANTHROPIC_LIVE_TEST=1 to run against the live Anthropic API")
	}
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		t.Fatal("ANTHROPIC_API_KEY is not set")
	}

	c := NewClient("", WithAPIKeyProvider(func() (string, error) { return apiKey, nil }))

	// A system prompt long enough to clear every model's minimum cacheable
	// prefix (512-4096 tokens, docs/ANTHROPIC-INTEGRATION.md's "Caching")
	// so the second request of each model's pair can show a cache hit.
	var filler strings.Builder
	filler.WriteString("You are a terse coding agent embedded in an automated test. ")
	for i := 0; i < 400; i++ {
		fmt.Fprintf(&filler, "Rule %d: always call the requested tool before answering in prose. ", i)
	}
	systemPrompt := filler.String()

	tool := wire.Tool{
		Type: "function",
		Function: wire.ToolFunction{
			Name:        "get_time",
			Description: "Returns the current time in a named city.",
			Parameters:  json.RawMessage(`{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}`),
		},
	}

	models := []string{ModelOpus55, ModelSonnet5, ModelFable51}
	for _, model := range models {
		t.Run(model, func(t *testing.T) {
			runTwoSubTurns(t, c, model, systemPrompt, tool, "low",
				"What time is it in Hobart? Use the get_time tool, then answer in one short sentence.")
		})
	}

	// "low" effort produced no thinking block on any of the three models
	// above (see docs/OBSERVED.md) — settle the plan's open question about
	// more than one thinking block in a response with a prompt shaped to
	// trigger real reasoning, at "high" effort, on the two models whose
	// preserved-thinking prefix check the plan calls out
	// (docs/ANTHROPIC-INTEGRATION.md's External facts table).
	for _, model := range []string{ModelOpus55, ModelSonnet5} {
		t.Run(model+"_high_effort_thinking", func(t *testing.T) {
			runTwoSubTurns(t, c, model, systemPrompt, tool, "high",
				"Work through this step by step: what is 47 times 89, minus 100? "+
					"Then call the get_time tool for Hobart and report both the arithmetic answer and the time.")
		})
	}

	t.Run("web_search_on_sonnet5", func(t *testing.T) {
		runWebSearch(t, c, systemPrompt)
	})
}

func runTwoSubTurns(t *testing.T, c *Client, model, systemPrompt string, tool wire.Tool, effort, question string) {
	items := []wire.Item{
		wire.SystemItem(systemPrompt),
		wire.UserItem(question),
	}
	intent := wire.ChatIntent{Model: model, Items: items, Effort: effort, MaxTokens: 2048, Tools: []wire.Tool{tool}}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	events, err := c.StreamChatCompletion(ctx, intent)
	if err != nil {
		t.Fatalf("request 1: StreamChatCompletion: %v", err)
	}

	var providerBlocks json.RawMessage
	var toolCallID, toolCallName string
	var thinkingBlockCount int
	assembler := wire.NewToolCallAssembler()
	for e := range events {
		switch e.Type {
		case wire.EventToolCallDelta:
			assembler.Add(e.ToolCall)
		case wire.EventProviderBlocks:
			providerBlocks = e.ProviderBlocks
			var blocks []rawContentBlock
			json.Unmarshal(providerBlocks, &blocks)
			for _, b := range blocks {
				if b.Type == "thinking" {
					thinkingBlockCount++
				}
			}
		case wire.EventUsage:
			t.Logf("request 1 usage: prompt=%d cache_read=%d cache_write=%d completion=%d",
				e.Usage.PromptTokens, e.Usage.CachedTokens, e.Usage.CacheWriteTokens, e.Usage.CompletionTokens)
		case wire.EventError:
			t.Fatalf("request 1: %v", e.Err)
		}
	}
	calls := assembler.Finalize()
	if len(calls) != 1 {
		t.Fatalf("request 1: got %d tool calls, want 1: %+v", len(calls), calls)
	}
	toolCallID, toolCallName = calls[0].ID, calls[0].Name
	t.Logf("request 1: tool call %s(%s), thinking blocks in this response = %d, raw blocks = %s",
		toolCallName, calls[0].Arguments, thinkingBlockCount, truncate(string(providerBlocks), 300))

	// Second sub-turn: replay the raw blocks (thinking included) verbatim,
	// plus the tool result, and confirm the same byte-identical system
	// prompt now shows a cache hit.
	reasoningItem := wire.ReasoningItem("")
	reasoningItem.ProviderBlocks = providerBlocks
	items2 := append(items,
		reasoningItem,
		wire.FunctionCallItem(toolCallID, toolCallName, calls[0].Arguments),
		wire.FunctionCallOutputItem(toolCallID, "14:32 ACST", ""),
	)
	intent2 := wire.ChatIntent{Model: model, Items: items2, Effort: effort, MaxTokens: 1024, Tools: []wire.Tool{tool}}

	ctx2, cancel2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel2()
	events2, err := c.StreamChatCompletion(ctx2, intent2)
	if err != nil {
		t.Fatalf("request 2: StreamChatCompletion: %v", err)
	}
	var content strings.Builder
	var cacheRead, promptTokens int
	for e := range events2 {
		switch e.Type {
		case wire.EventContentDelta:
			content.WriteString(e.Content)
		case wire.EventUsage:
			cacheRead = e.Usage.CachedTokens
			promptTokens = e.Usage.PromptTokens
			t.Logf("request 2 usage: prompt=%d cache_read=%d cache_write=%d completion=%d",
				e.Usage.PromptTokens, e.Usage.CachedTokens, e.Usage.CacheWriteTokens, e.Usage.CompletionTokens)
		case wire.EventError:
			t.Fatalf("request 2 (thinking replay): %v", e.Err)
		}
	}
	t.Logf("request 2 answer: %s", content.String())
	t.Logf("cache: read=%d of prompt=%d tokens (%.1f%%)", cacheRead, promptTokens, 100*float64(cacheRead)/float64(promptTokens))
}

func runWebSearch(t *testing.T, c *Client, systemPrompt string) {
	items := []wire.Item{
		wire.SystemItem(systemPrompt),
		wire.UserItem("Use web search to find today's top Hacker News post title. Keep the answer to one sentence."),
	}
	intent := wire.ChatIntent{Model: ModelSonnet5, Items: items, Effort: "low", MaxTokens: 2048}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	events, err := c.StreamChatCompletion(ctx, intent)
	if err != nil {
		t.Fatalf("StreamChatCompletion: %v", err)
	}
	var content strings.Builder
	var providerBlocks json.RawMessage
	var sawServerToolUse, sawServerToolResult bool
	for e := range events {
		switch e.Type {
		case wire.EventContentDelta:
			content.WriteString(e.Content)
		case wire.EventProviderBlocks:
			providerBlocks = e.ProviderBlocks
			var blocks []struct {
				Type string `json:"type"`
			}
			json.Unmarshal(providerBlocks, &blocks)
			for _, b := range blocks {
				if b.Type == "server_tool_use" {
					sawServerToolUse = true
				}
				if strings.HasSuffix(b.Type, "_tool_result") {
					sawServerToolResult = true
				}
			}
		case wire.EventError:
			t.Fatalf("web search request: %v", e.Err)
		}
	}
	t.Logf("web search answer: %s", content.String())
	t.Logf("saw server_tool_use=%v, saw *_tool_result=%v", sawServerToolUse, sawServerToolResult)
	if !sawServerToolUse {
		t.Log("model answered without calling web_search — not a failure, just nothing to observe about server-tool replay this run")
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
